server:
  port: 9001

### 多数据源
spring:
  redis:
    database: 0 # Redis数据库索引（默认为0）
    host: 192.168.209.11
    port: 6379
    password: 322@*sdaAs
    timeout: 600 #Springboot2.0 不能设置为0
    lettuce:
      pool:
        max-active: 50 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8  # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
  redis2:
    database: 1
    host: 192.168.209.12
    port: 6379
    password: 322@*sdaAs
    timeout: 600