server:
  servlet:
    contextPath: /
  port: 9000

spring:
  application:
    name: gateway-test
  cloud:
    ## 配置路由地址
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
        - id: test
          uri: lb://test
          predicates: # 断言
#            # 路径匹配 test服务下的test接口
             # 请求路径 http://localhost:9000/test/date
            - Path=/test/**
        - id: openfeign-test
          uri: lb://openfeign-test
          predicates: # 断言
              - Path=/openfeign-test/**
          filters:
            # 匹配 openfeign-test 服务的 /test接口
            # 请求路径 http://localhost:9000/openfeign-test/test/date
            - StripPrefix=1
    nacos:
      server-addr: localhost:8848
